site_name: My Guide
site_url: https://galeiro.github.io
nav:
    - Welcome: index.md
    - MKDocs + Github: mkdocs.md

theme:
  name: material
  palette:
    scheme: green
    primary: green
    accent: black